<a href="https://colab.research.google.com/github/get-ayush/PandasDataframe/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy Array


In [ ]:
import numpy as np
a= np.array([2,4,5])
print(a)
print(type(a))

[2 4 5]
<class 'numpy.ndarray'>


Creating 2D & 3D Array

In [ ]:
b = np.array([[5,6,7],[8,9,10]])#2d Array
print(b)

c= np.array([[[45,456,78],[894,41,45],[56,12,77]]])#3d Array
print(c)

[[ 5  6  7]
 [ 8  9 10]]
[[[ 45 456  78]
  [894  41  45]
  [ 56  12  77]]]


Data Type Array #dtype

In [ ]:
a = np.array([1,2,3],dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


arange Function

In [ ]:
p = np.arange(1,11)#arange
print(p)

[ 1  2  3  4  5  6  7  8  9 10]


With Reshape

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

np.ones & np.zeros

In [ ]:
a=np.ones([3,4])
b=np.zeros([3,4])
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.random

In [ ]:
np.random.random([3,4])

array([[0.18806038, 0.61299646, 0.45323717, 0.49051056],
       [0.63415868, 0.74041849, 0.5902006 , 0.58876565],
       [0.08159841, 0.11852827, 0.15014708, 0.76852834]])

np.linspace

In [ ]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

Identity Matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [ ]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(1,13).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)
a2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Ndim :** Finds out the dimension of the Array

In [ ]:
a3.ndim

3

**Shape :** Finds out the rows and Column in Array

In [ ]:
a2.shape

(4, 3)

**SiZe :** Number of Items in Array

In [ ]:
a2.size
# print(a2)

12

**Itemsize**: bytes used to store data type

1.   List item
2.   List item



In [ ]:
a1.itemsize

4

**dtype**: data type

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


# **Changing datatype**

Astype : Change the datatype of the element

In [ ]:
a2 = a2.astype(np.int32)
print(a2.dtype)

int32


# **Array Opererations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

Scalar Operations

In [ ]:
a1 * 2 #Multiplication
a1 + 2 #Addition
a1 / 2 #Division

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Relational Operation

In [ ]:
a1 == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

Vector Arithmetic Operations

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# **Array Functions**

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[55. 47. 39.]
 [45. 32. 97.]
 [22.  2. 61.]]


Max/Min/Sum/Prod : Axis = 0 for column wise and Axis = 1 for row wise

> Add blockquote



In [ ]:
import numpy as np
a= np.array([2,4,5])
print(a)
print(type(a))

[2 4 5]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[5,6,7],[8,9,10]])#2d Array
print(b)

c= np.array([[[45,456,78],[894,41,45],[56,12,77]]])#3d Array
print(c)

[[ 5  6  7]
 [ 8  9 10]]
[[[ 45 456  78]
  [894  41  45]
  [ 56  12  77]]]


In [ ]:
a = np.array([1,2,3],dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
p = np.arange(1,11)#arange
print(p)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a=np.ones([3,4])
b=np.zeros([3,4])
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
np.random.random([3,4])

array([[0.5560427 , 0.20491798, 0.24470424, 0.18150801],
       [0.70022018, 0.38185622, 0.5105647 , 0.33699334],
       [0.63740692, 0.60716827, 0.91813228, 0.93271512]])

In [ ]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(1,13).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a3.ndim

3

In [ ]:
a2.shape

(4, 3)

In [ ]:
a2.size

12

In [ ]:
a1.itemsize

4

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


In [ ]:
a2 = a2.astype(np.int32)
print(a2.dtype)

int32


In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a1 * 2 #Multiplication
a1 + 2 #Addition
a1 / 2 #Division

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# np.prod(a1)
# np.sum(a1)
x =np.max(a1,axis=0)
y =np.max(a1, axis = 1)
print(x)
print(y)

[ 8  9 10 11]
[ 3  7 11]


In [ ]:
a1 == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

Slicing and Indexing

3d Slicing

In [ ]:
a2 = np.arange(0,12).reshape(3,4)


In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1::2,0::3]

array([[4, 7]])

In [ ]:
a2[0:2 ,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

NDITER function for looping and printing a 3d Matriz in 1d

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Transpose Converts Rows into column and column into rows

In [ ]:
print(a2)
# np.transpose(a2)
# a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Ravel Convert 3d Arrays to 1D ARRAY

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking Can add up the array vertically or horizontal

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5,a4,a5))#Horizontal Stack
np.vstack((a4,a5,a4,a5))#Verical Stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting Horizontally and vertically split

In [ ]:
np.hsplit(a5,4)#horizontal split
np.vsplit(a5,3)#Vertical Split

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]